ASWAQ/Controllers/AdminController.cs
using ASWAQ.ViewModels;
using BLL.Interfaces;
using DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ASWAQ.Controllers
{
    [Authorize(Roles = "Supervisor")]
    public class AdminController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IEmployeeRepository employeeRepository;
        private readonly ISectionRepository sectionRepository;
        private readonly IWorkInRepository workInRepository;
        private readonly IProductRepository productRepository;

        public AdminController(UserManager<ApplicationUser> _userManager, IEmployeeRepository _employeeRepository, ISectionRepository _sectionRepository, IWorkInRepository _workInRepository,IProductRepository _productRepository )
        {
            userManager = _userManager;
            employeeRepository = _employeeRepository;
            sectionRepository = _sectionRepository;
            workInRepository = _workInRepository;
            productRepository = _productRepository;
        }


        public IActionResult Index()
        {
            // var roles = await roleManager.Roles.ToListAsync();

            return View();
        }

        public async Task<IActionResult> Employees()
        {
            string superVisor = userManager.GetUserId(User);

            return View(await employeeRepository.GetSvEmployeesByIdAsync(superVisor));
        }

        public async Task<IActionResult> AddEmployee()
        {
            ViewBag.Sections = await sectionRepository.GetAll();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddEmployee(AddEmployeeViewModel newEmp)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser newUser = new()
                {
                    UserName = newEmp.UserName,
                };

                IdentityResult result = await userManager.CreateAsync(newUser, newEmp.Password);
                if (result.Succeeded)
                {
                    string UserID = userManager.GetUserId(User);

                    Employee employee = new() { Id = newUser.Id, Salary = newEmp.Salary, SuperVisor_Id = UserID };
                    employeeRepository.Create(employee);

                    foreach (var SectionID in newEmp.SectionsId)
                    {
                        await workInRepository.CreateAsync(new WorkIn() { EID = employee.Id, SID = SectionID });
                    }

                    return RedirectToAction(nameof(Employees));
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View(newEmp);
        }


        public async Task<IActionResult> EditEmployee(string EmpID)
        {
            Employee employee = await employeeRepository.GetByKeyAsync(EmpID);

            ViewBag.Sections = await sectionRepository.GetAll();

            EditEmployeeViewModel editEmployee = new()
            {

                Id = employee.Id,
                UserName = employee.User.UserName,
                Salary = employee.Salary
            };

            foreach (var emp in employee.EmployeeSections)
            {
                editEmployee?.SectionsId?.Add(emp.SID);
            }


            return View(editEmployee);
        }

        [HttpPost]
        public async Task<IActionResult> EditEmployee(EditEmployeeViewModel editEmployee)
        {

            if (ModelState.IsValid)
            {
                await employeeRepository.Update(editEmployee.Id, new Employee()
                {
                    Salary = editEmployee.Salary,
                    SuperVisor_Id = userManager.GetUserId(User)
                });

                await workInRepository.DeleteAllAsync(editEmployee.Id);

                foreach (var SectionID in editEmployee.SectionsId)
                {
                    await workInRepository.CreateAsync(new WorkIn() { EID = editEmployee.Id, SID = SectionID });
                }

                ApplicationUser user = await userManager.FindByIdAsync(editEmployee.Id);
                user.UserName = editEmployee.UserName;
                IdentityResult result = await userManager.UpdateAsync(user);

                return RedirectToAction(nameof(Employees));
            }

            return RedirectToAction(nameof(EditEmployee), new { EmpId = editEmployee.Id });
        }





        public async Task<IActionResult> Sections()
        {
            return View(await sectionRepository.GetAll());
        }

        public async Task<IActionResult> Section(string secName)
        {
            return View(await sectionRepository.GetSectionWithProductsAsync(secName));
        }        

        public IActionResult AddSection()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddSection(AddSectionViewModel model)
        {
            if (ModelState.IsValid)
            {
                Section section = new() { Name = model.Name };

                using (var memorystream = new MemoryStream())
                {
                    await model.Image.CopyToAsync(memorystream);
                    section.Image = memorystream.ToArray();

                    sectionRepository.Create(section);
                }

                return RedirectToAction(nameof(AddSection));

            }

            return View(model);
        }

        public async Task<IActionResult> RemoveSection(int sectionID)
        {
            await sectionRepository.Delete(sectionID);

            return RedirectToAction(nameof(Sections));
        }





        public IActionResult AddProduct(int SectionID)
        {
            ViewBag.SectionID = SectionID;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct(AddProductViewModel addProduct)
        {
            if (ModelState.IsValid)
            {
                Product product = new() { Name = addProduct.Name, Description = addProduct.Description, Price = addProduct.Price, SID = addProduct.SectionID };

                using (MemoryStream memoryStream = new())
                {
                    await addProduct.Image.CopyToAsync(memoryStream);

                    product.Image = memoryStream.ToArray();

                    await productRepository.Create(product);

                    return RedirectToAction(nameof(AddProduct), new {SectionID = addProduct.SectionID});
                }
            }

            return View(addProduct);
        }        

    }
}

ASWAQ/Controllers/CartController.cs
using ASWAQ.Controllers;
using BLL.Interfaces;
using DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net.Mail;

namespace SuperMarket.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IOrderRepository orderRepository;
        private readonly ISectionRepository sectionRepository;
        private readonly IProductRepository productRepository;
        private readonly ICustomerRepository customerRepository;

        public CartController(UserManager<ApplicationUser> _userManager, IOrderRepository _orderRepository, ISectionRepository _sectionRepository, IProductRepository _productRepository, ICustomerRepository _customerRepository)
        {
            userManager = _userManager;
            orderRepository = _orderRepository;
            sectionRepository = _sectionRepository;
            productRepository = _productRepository;
            customerRepository = _customerRepository;
        }

        public async Task<IActionResult> Index()
        {

            string id = userManager.GetUserId(User);            

            List<Order> Cart = await orderRepository.GetAllByCustomerID(id);

            decimal TotalPrice = await customerRepository.GetTotalPriceAsync(id);

            ViewBag.TotalPrice = Math.Round(TotalPrice, 2).ToString();

            return View(Cart);
        }

        public async Task<IActionResult> ChangeCartAction(int ID, int change = 1, bool Add = false)
        {

            string CustomerID = userManager.GetUserId(User);            

            Order existsOrder = await orderRepository.GetByKeys(CustomerID, ID);

            if (existsOrder.ProductID != 0)
            {

                existsOrder.Total += existsOrder.Total + change >= 1 ? change : 0;
                orderRepository.Update(existsOrder.CustomerID, existsOrder.ProductID, existsOrder);

                if (!Add)
                {
                    decimal TotalPrice = await customerRepository.GetTotalPriceAsync(CustomerID);

                    TotalPrice = Math.Round(TotalPrice, 2);

                    return Json(new { Total = existsOrder.Total, TotalPrice = TotalPrice.ToString() });
                }

            }

            else
            {
                Order order = new Order() { CustomerID = CustomerID, ProductID = ID, Total = change, OrderDate = DateTime.Now };
                orderRepository?.Create(order);
                
            }

            string Name = productRepository.GetSecNameOfProd(ID);
            return RedirectToAction(nameof(SectionController.Index), nameof(SectionController).Replace("Controller", ""), new { Name });

        }
        
        public async Task<IActionResult> RemoveProduct(string CustomerID, int ProductID)
        {            
            Order order = await orderRepository.GetByKeys(CustomerID, ProductID);            

            orderRepository.Delete(order.CustomerID, order.ProductID);            

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> CheckOut()
        {
            string CustomerID = userManager.GetUserId(User);
            
            decimal TotalPrice = await customerRepository.GetTotalPriceAsync(CustomerID);
            if (TotalPrice == 0)
            {
                return RedirectToAction(nameof(Index));
            }

            ViewBag.TotalPrice = Math.Round(TotalPrice, 2).ToString();
                                       
            Customer customer = await customerRepository.GetByKeyAsync(CustomerID);            

            return View(customer);                     
        }
        
        public async Task<IActionResult> FinalCheckOut()
        {            

            bool deleted = await orderRepository.DeleteAll(userManager.GetUserId(User));
            if (deleted)
            {
                return RedirectToAction("Index", "Home");
            }

            else return RedirectToAction(nameof(CheckOut));
        }
    }
}

ASWAQ/Views/Shared/_CartPartialView.cshtml
@inject ICustomerRepository customerRepository
@inject UserManager<ApplicationUser> userManager

@if (User.Identity?.IsAuthenticated == true)
{
    <li class="nav-item">
        <div>
            <a class="btn btnbtn-group" asp-action="Index" asp-controller="Cart">
                <img class="Cart" src="~/images/cart.jpg" />
                <label style="color:red;">@await customerRepository.GetOrdersCount(userManager.GetUserId(User))</label>
            </a>
        </div>
    </li>
}

ASWAQ/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASWAQ</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/ASWAQ.styles.css" asp-append-version="true" />    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="/css/Sheet.css" asp-append-version="true" />

    <style>
        @RenderSection("Main",false)
    </style>
    
</head>
<body>
    <div class="MainLayout">
        <header style="opacity:80%">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow bg-white  ">
                <div class="container-fluid">
                    <a class="navbar-brand Aswaq" asp-controller="@nameof(HomeController).Replace("Controller","")" asp-action="@nameof(HomeController.Index)"><h2>ASWAQ</h2></a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                        <ul class="navbar-nav flex-grow-1">
                            <form>
                                <li class="nav-item">
                                    <input class="Serch_Input form-control" type="text" />
                                    <input class="btn btn-toolbar Serch_Submit" type="submit" value="Search" />
                                </li>

                            </form>

                            <partial name="_CartPartialView"></partial>

                        </ul>

                        <partial name="_UserStatePartialView"></partial>


                    </div>
                </div>
            </nav>
        </header>
    </div>

    <div >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted boorder" >
        <div class="container">
            @RenderSection("Footer",false)            
        </div>
    </footer>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASWAQ/Views/Shared/_UserStatePartialView.cshtml
@inject UserManager<ApplicationUser> usermanager

@if (User.Identity?.IsAuthenticated == false)
{
    <ul class="navbar-nav">

        <li class="nav-item">
            <a class="btn btn-outline-dark LogAndSigin" asp-controller="@nameof(AccountController).Replace("Controller","")" asp-action="@nameof(AccountController.Login)" style="margin-right:40px">Login</a>
        </li>

        <li class="nav-item">
            <a class="btn btn-outline-dark LogAndSigin" asp-controller="@nameof(AccountController).Replace("Controller","")" asp-action="@nameof(AccountController.Register)">Register</a>
        </li>

    </ul>
}
else
{    
    @if (User.Claims.Any(i => i.Value == "Supervisor"))
    {
        <ul class="navbar-nav">

            <li>
                <div>
                    <a asp-action="Profile" asp-controller="Account" class="btn btn-group">
                        <img class="UserIcon" src="~/Images/UserIcone.jpg" />

                        <h5 class="FName">@usermanager.GetUserAsync(User).Result.FirstName</h5>
                    </a>
                </div>
            </li>

            <li class="nav-item">
                <a class="btn btn-outline-dark LogAndSigin" asp-controller="Admin" asp-action="index" style="margin-right:40px;margin-top:10px">Admin</a>
            </li>            

            <li class="nav-item">
                <a class="btn btn-outline-danger LotOut" asp-controller="@nameof(AccountController).Replace("Controller","")" asp-action="@nameof(AccountController.Logout)">LOGOUT</a>
            </li>

        </ul>
    }
    else
    {
        <ul class="navbar-nav">
            <li>
                <div>
                    <a asp-action="Profile" asp-controller="Account" class="btn btn-group">
                        <img class="UserIcon" src="~/Images/UserIcone.jpg" />
                        <h5 class="FName">@usermanager.GetUserAsync(User).Result.FirstName</h5>
                    </a>
                </div>
            </li>

            <li class="nav-item">
                <a class="btn btn-outline-danger LotOut" asp-controller="@nameof(AccountController).Replace("Controller","")" asp-action="@nameof(AccountController.Logout)">LOGOUT</a>
            </li>        

        </ul>
    }
}